# Generated by Django 5.0.6 on 2024-06-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
